import { dataSource } from '../../../database';
import AppError from '../../../errors/AppError';
import ContractRepository from '../repositories/contract.repository';
import GetContractService from './get.service';
import { ContractQueryDto, ContractResponseDto } from '../dtos';

// Reopens a completed contract that still has instalments left (e.g. completed early by mistake).
// Invoices missed while it was completed are generated by the scheduled job, one per run.
export default class ReactivateContractService {
  private contractRepository: ContractRepository;

  constructor() {
    this.contractRepository = new ContractRepository(dataSource);
  }

  async execute(dto: ContractQueryDto): Promise<ContractResponseDto> {
    const contract = await this.contractRepository.findById(dto.id, dto.userId);
    if (!contract) throw new AppError('Contract not found', 404);
    if (contract.status !== 'completed') throw new AppError('Contract is not completed', 400);
    if (contract.instalments > 0 && contract.instalmentsDone >= contract.instalments) {
      throw new AppError('All instalments were generated; increase instalments to reactivate the contract', 400);
    }

    contract.status = 'active';
    await this.contractRepository.save(contract);

    return new GetContractService().execute({ id: contract.id, userId: dto.userId });
  }
}
