import { dataSource } from '../../../database';
import AppError from '../../../errors/AppError';
import ContractRepository from '../repositories/contract.repository';
import GetContractService from './get.service';
import { ContractQueryDto, ContractResponseDto } from '../dtos';

export default class RestoreContractService {
  private contractRepository: ContractRepository;

  constructor() {
    this.contractRepository = new ContractRepository(dataSource);
  }

  async execute(dto: ContractQueryDto): Promise<ContractResponseDto> {
    const contract = await this.contractRepository.findOne({
      where: { id: dto.id, user: { id: dto.userId } },
      withDeleted: true,
    });
    if (!contract) throw new AppError('Contract not found', 404);
    if (!contract.deletedAt) throw new AppError('Contract is not deleted', 400);

    // Deleting sets the status to cancelled; restore the status the contract would have otherwise.
    // Invoices missed while deleted are generated by the scheduled job, one per run.
    contract.status =
      contract.instalments > 0 && contract.instalmentsDone >= contract.instalments ? 'completed' : 'active';
    contract.deletedAt = null as unknown as Date;
    await this.contractRepository.save(contract);

    return new GetContractService().execute({ id: contract.id, userId: dto.userId });
  }
}
