import { useState } from "react";
import { useParams, useNavigate, Link } from "react-router-dom";
import {
  ArrowLeft,
  TrendingDown,
  TrendingUp,
  RefreshCw,
  CircleCheck,
  CirclePlay,
} from "lucide-react";
import {
  useContract,
  useDeleteContract,
  useRestoreContract,
  useCompleteContract,
  useReactivateContract,
  useGenerateContractInvoice,
  ContractStatusBadge,
  ContractFormDialog,
} from "@/features/contracts";
import { WalletLink } from "@/features/wallets";
import { DeletedBanner } from "@/components/DeletedBanner";
import { formatCurrency, formatDate } from "@/lib/format";
import { cn } from "@/lib/utils";

export default function ContractDetailPage() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const [showEdit, setShowEdit] = useState(false);

  const { data: contract, isLoading, error } = useContract(id!);
  const deleteContract = useDeleteContract();
  const generateInvoice = useGenerateContractInvoice();
  const restoreContract = useRestoreContract();
  const completeContract = useCompleteContract();
  const reactivateContract = useReactivateContract();

  const actionError =
    deleteContract.error ||
    generateInvoice.error ||
    completeContract.error ||
    reactivateContract.error;

  async function handleComplete() {
    if (
      !confirm(
        `Complete contract "${contract?.name}"?\n\nInvoices already generated are kept, but no new ones will be generated.`,
      )
    )
      return;
    await completeContract.mutateAsync(contract!.id!);
  }

  async function handleReactivate() {
    if (
      !confirm(
        `Reactivate contract "${contract?.name}"?\n\nInvoices missed while it was completed will be generated by the scheduled job, one per run.`,
      )
    )
      return;
    await reactivateContract.mutateAsync(contract!.id!);
  }

  async function handleCancel() {
    if (!confirm(`Cancel contract "${contract?.name}"?`)) return;
    await deleteContract.mutateAsync(contract!.id!);
    navigate("/contracts");
  }

  async function handleGenerate() {
    if (
      !confirm(
        `Manually generate the next invoice for "${contract?.name}" now?\n\nThis will advance the instalment counter and next due date.`,
      )
    )
      return;
    await generateInvoice.mutateAsync(contract!.id!);
  }

  if (isLoading) {
    return (
      <div className="space-y-4 max-w-2xl">
        <div className="h-8 w-48 rounded bg-gray-200 animate-pulse" />
        <div className="h-40 rounded-lg bg-gray-200 animate-pulse" />
        <div className="h-48 rounded-lg bg-gray-200 animate-pulse" />
      </div>
    );
  }

  if (error || !contract) {
    return (
      <div className="space-y-4">
        <button
          onClick={() => navigate("/contracts")}
          className="inline-flex items-center gap-1.5 text-sm text-gray-500 hover:text-gray-700"
        >
          <ArrowLeft size={15} />
          Back
        </button>
        <p className="text-sm text-red-600">
          {error?.message ?? "Contract not found."}
        </p>
      </div>
    );
  }

  const isPayable = contract.type === "payable";
  const isDeleted = !!contract.deletedAt;
  const totalInstalments = contract.instalments ?? 0;
  const done = contract.instalmentsDone ?? 0;
  const isInfinite = totalInstalments === 0;
  // The backend only reactivates completed contracts that still have instalments left
  const canReactivate =
    contract.status === "completed" && (isInfinite || done < totalInstalments);
  const progressPct =
    !isInfinite && totalInstalments > 0
      ? Math.min(100, (done / totalInstalments) * 100)
      : null;

  const invoices = contract.invoices ?? [];
  const currency = contract.total?.currency ?? "";

  const invoiceStatusStyles: Record<string, string> = {
    pending: "bg-gray-100 text-gray-600",
    partial: "bg-yellow-100 text-yellow-700",
    paid: "bg-green-100 text-green-700",
    cancelled: "bg-slate-100 text-slate-500",
  };

  return (
    <div className="space-y-6 max-w-2xl">
      <div className="flex items-center gap-3">
        <button
          onClick={() => navigate(-1)}
          className="p-1.5 rounded hover:bg-gray-100 text-gray-500 transition-colors"
        >
          <ArrowLeft size={18} />
        </button>
        <h1 className="text-xl font-semibold text-gray-900">Contract Detail</h1>
      </div>

      {isDeleted && (
        <DeletedBanner
          resource="contract"
          deletedAt={contract.deletedAt!}
          onRestore={() => restoreContract.mutate(contract.id!)}
          isRestoring={restoreContract.isPending}
          error={restoreContract.error}
        />
      )}

      {/* Header card */}
      <div className="bg-white rounded-lg border border-gray-200 p-5 space-y-4">
        <div className="flex items-start justify-between gap-4">
          <div className="space-y-1 min-w-0">
            <p className="text-lg font-semibold text-gray-900 truncate">
              {contract.name}
            </p>
            {contract.contact?.name && (
              <p className="text-sm text-gray-500">{contract.contact.name}</p>
            )}
            <div className="flex items-center gap-2 mt-1">
              <span
                className={cn(
                  "inline-flex items-center gap-1 text-xs font-medium",
                  isPayable ? "text-orange-600" : "text-green-600",
                )}
              >
                {isPayable ? (
                  <TrendingDown size={12} />
                ) : (
                  <TrendingUp size={12} />
                )}
                {isPayable ? "Payable" : "Receivable"}
              </span>
              <ContractStatusBadge status={contract.status} />
            </div>
          </div>
          <div className="text-right shrink-0">
            <p className="text-2xl font-bold text-gray-900">
              {formatCurrency(
                contract.total?.amount ?? 0,
                contract.total?.currency ?? "",
              )}
            </p>
            <p className="text-xs text-gray-500 mt-0.5">per instalment</p>
          </div>
        </div>

        {/* Progress bar (finite contracts) */}
        {progressPct !== null && (
          <div className="space-y-1">
            <div className="flex justify-between text-xs text-gray-500">
              <span>
                {done} / {totalInstalments} instalments
              </span>
              <span>{progressPct.toFixed(0)}% complete</span>
            </div>
            <div className="h-2 bg-gray-100 rounded-full overflow-hidden">
              <div
                className={cn(
                  "h-full rounded-full transition-all",
                  progressPct >= 100 ? "bg-green-500" : "bg-blue-500",
                )}
                style={{ width: `${progressPct}%` }}
              />
            </div>
          </div>
        )}

        {isInfinite && (
          <p className="text-xs text-gray-500">
            Recurring — {done} instalment{done !== 1 ? "s" : ""} generated so
            far
          </p>
        )}

        {/* Detail grid */}
        <dl className="grid grid-cols-[auto_1fr] gap-x-4 gap-y-2 text-sm border-t border-gray-100 pt-3">
          <dt className="text-gray-500">Cycle</dt>
          <dd className="text-gray-900">
            Every {contract.cycleMonths}{" "}
            {contract.cycleMonths === 1 ? "month" : "months"}
          </dd>
          {contract.wallet && (
            <>
              <dt className="text-gray-500">Wallet</dt>
              <dd>
                <WalletLink wallet={contract.wallet} />
              </dd>
            </>
          )}
          <dt className="text-gray-500">First due</dt>
          <dd className="text-gray-900">
            {contract.firstDueDate ? formatDate(contract.firstDueDate) : "—"}
          </dd>
          {contract.status === "active" && contract.nextDueDate && (
            <>
              <dt className="text-gray-500">Next due</dt>
              <dd className="text-gray-900">
                {formatDate(contract.nextDueDate)}
              </dd>
            </>
          )}
          {contract.description && (
            <>
              <dt className="text-gray-500">Description</dt>
              <dd className="text-gray-900">{contract.description}</dd>
            </>
          )}
          {contract.notes && (
            <>
              <dt className="text-gray-500">Notes</dt>
              <dd className="text-gray-900 whitespace-pre-wrap">
                {contract.notes}
              </dd>
            </>
          )}
        </dl>

        {contract.tags && contract.tags.length > 0 && (
          <div className="flex flex-wrap gap-1.5 pt-1">
            {contract.tags.map((tag) => (
              <span
                key={tag.id}
                className="text-xs px-2 py-0.5 rounded-full bg-gray-100 text-gray-600"
              >
                {tag.name}
              </span>
            ))}
          </div>
        )}

        {actionError && (
          <p className="text-sm text-red-600">{actionError.message}</p>
        )}

        {/* Actions */}
        {!isDeleted && (
          <div className="flex flex-wrap gap-2 pt-1 border-t border-gray-100">
            {contract.status !== "cancelled" && (
              <button
                onClick={() => setShowEdit(true)}
                className="px-3 py-1.5 text-sm border border-gray-200 rounded-md text-gray-700 hover:bg-gray-50 transition-colors"
              >
                Edit
              </button>
            )}
            {contract.status === "active" && (
              <>
                <button
                  onClick={handleGenerate}
                  disabled={generateInvoice.isPending}
                  className="flex items-center gap-1.5 px-3 py-1.5 text-sm bg-green-600 text-white rounded-md hover:bg-green-700 disabled:opacity-50 transition-colors"
                >
                  <RefreshCw size={13} />
                  {generateInvoice.isPending ? "Generating..." : "Next Invoice"}
                </button>
                <button
                  onClick={handleComplete}
                  disabled={completeContract.isPending}
                  className="flex items-center gap-1.5 px-3 py-1.5 text-sm border border-gray-200 rounded-md text-gray-700 hover:bg-gray-50 disabled:opacity-50 transition-colors"
                  title="End the contract without deleting it"
                >
                  <CircleCheck size={13} />
                  {completeContract.isPending ? "Completing..." : "Complete"}
                </button>
                <button
                  onClick={handleCancel}
                  disabled={deleteContract.isPending}
                  className="ml-auto px-3 py-1.5 text-sm border border-red-200 rounded-md text-red-600 hover:bg-red-50 disabled:opacity-50 transition-colors"
                >
                  {deleteContract.isPending
                    ? "Cancelling..."
                    : "Cancel Contract"}
                </button>
              </>
            )}
            {canReactivate && (
              <button
                onClick={handleReactivate}
                disabled={reactivateContract.isPending}
                className="flex items-center gap-1.5 px-3 py-1.5 text-sm bg-blue-600 text-white rounded-md hover:bg-blue-700 disabled:opacity-50 transition-colors"
              >
                <CirclePlay size={13} />
                {reactivateContract.isPending
                  ? "Reactivating..."
                  : "Reactivate"}
              </button>
            )}
          </div>
        )}
        {contract.status === "completed" && !canReactivate && !isDeleted && (
          <p className="text-xs text-gray-500">
            All instalments were generated. Edit the contract and increase the
            instalments to continue it.
          </p>
        )}
      </div>

      {/* Generated invoices */}
      <div className="space-y-3">
        <h2 className="text-sm font-medium text-gray-700">
          Generated Invoices
        </h2>

        {invoices.length === 0 ? (
          <p className="text-sm text-gray-400">No invoices generated yet.</p>
        ) : (
          <div className="bg-white rounded-lg border border-gray-200 overflow-hidden">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-gray-200 bg-gray-50">
                  <th className="text-left px-4 py-2.5 font-medium text-gray-600">
                    Due date
                  </th>
                  <th className="text-left px-4 py-2.5 font-medium text-gray-600 hidden sm:table-cell">
                    Issue date
                  </th>
                  <th className="text-left px-4 py-2.5 font-medium text-gray-600">
                    Status
                  </th>
                  <th className="text-right px-4 py-2.5 font-medium text-gray-600">
                    Amount
                  </th>
                  <th className="text-right px-4 py-2.5 font-medium text-gray-600 hidden sm:table-cell">
                    Paid
                  </th>
                  <th className="text-right px-4 py-2.5 font-medium text-gray-600">
                    Outstanding
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-100">
                {invoices.map((inv) => (
                  <tr
                    key={inv.id}
                    className="hover:bg-gray-50 transition-colors"
                  >
                    <td className="px-4 py-3">
                      <Link
                        to={`/invoices/${inv.id}`}
                        className="text-gray-900 hover:text-blue-600 hover:underline"
                      >
                        {inv.dueDate ? formatDate(inv.dueDate) : "—"}
                      </Link>
                    </td>
                    <td className="px-4 py-3 text-gray-600 hidden sm:table-cell">
                      {inv.issueDate ? formatDate(inv.issueDate) : "—"}
                    </td>
                    <td className="px-4 py-3">
                      <span
                        className={cn(
                          "inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium capitalize",
                          invoiceStatusStyles[inv.status ?? "pending"],
                        )}
                      >
                        {inv.status}
                      </span>
                    </td>
                    <td className="px-4 py-3 text-right font-medium text-gray-900 whitespace-nowrap">
                      {formatCurrency(
                        inv.total?.amount ?? 0,
                        inv.total?.currency ?? "",
                      )}
                    </td>
                    <td className="px-4 py-3 text-right text-gray-600 whitespace-nowrap hidden sm:table-cell">
                      {formatCurrency(
                        inv.paidAmount?.amount ?? 0,
                        inv.total?.currency ?? "",
                      )}
                    </td>
                    <td
                      className={cn(
                        "px-4 py-3 text-right whitespace-nowrap",
                        (inv.outstanding?.amount ?? 0) > 0
                          ? "font-medium text-gray-900"
                          : "text-gray-300",
                      )}
                    >
                      {(inv.outstanding?.amount ?? 0) > 0
                        ? formatCurrency(
                            inv.outstanding!.amount!,
                            inv.total?.currency ?? "",
                          )
                        : "—"}
                    </td>
                  </tr>
                ))}
              </tbody>
              <tfoot>
                <tr className="border-t border-gray-200 bg-gray-50 text-xs font-medium text-gray-700">
                  <td className="px-4 py-2.5" colSpan={2}>
                    <span className="sm:hidden">Totals</span>
                    <span className="hidden sm:inline">
                      Totals ({invoices.length} invoice
                      {invoices.length !== 1 ? "s" : ""})
                    </span>
                  </td>
                  <td className="hidden sm:table-cell" />
                  <td className="px-4 py-2.5 text-right whitespace-nowrap">
                    {formatCurrency(
                      contract.totalInvoiced?.amount ?? 0,
                      contract.totalInvoiced?.currency ?? currency,
                    )}
                  </td>
                  <td className="px-4 py-2.5 text-right whitespace-nowrap text-green-700 hidden sm:table-cell">
                    {formatCurrency(
                      contract.totalPaid?.amount ?? 0,
                      contract.totalPaid?.currency ?? currency,
                    )}
                  </td>
                  <td className="px-4 py-2.5 text-right whitespace-nowrap">
                    {formatCurrency(
                      contract.totalOutstanding?.amount ?? 0,
                      contract.totalOutstanding?.currency ?? currency,
                    )}
                  </td>
                </tr>
              </tfoot>
            </table>
          </div>
        )}
      </div>

      {showEdit && (
        <ContractFormDialog
          contract={contract}
          onClose={() => setShowEdit(false)}
        />
      )}
    </div>
  );
}
